from Embedding import Embeddings
from fasttext_embedding import Fasttext
from n_gram import NgramGenerator
from Nepali_tokenizer import  Tokenizer
from news_latest import UpdateNews
from ocr import OCR
from positional_encoding import PositionalEncoding
from preeti_unicode import preeti
from sentence_similar import  Avg_vector_similar
from spellcheck import Corrector
from stopword import Stopwords
from summerization import Summerize
from synonym import Synonym
from unicode_nepali import Unicode
